dist: trusty

language: java
jdk:
  - oraclejdk8   

notifications:
  email: false

matrix:
  include:
    - os: linux

    - os: linux
      env:
        CFLAGS="-march=x86-64"
        CPPFLAGS="-march=x86-64"
        ONEJAR="ON"
        ORG_GRADLE_PROJECT_TILEDB_S3="ON"

install:
  # Build and install extension module
  - ./gradlew assemble test
  # Build oneJar for contained dependencies
  - if [[ "${ONEJAR}" == "ON" ]]; then
     ./gradlew oneJar;
    fi

script:
  - ./gradlew checkFormat
  - ./gradlew test
