dist: trusty

language: java
jdk:
  - oraclejdk8

notifications:
  email: false

matrix:
  include:
    - os: linux

    - os: linux
      env:
        CFLAGS="-march=x86-64"
        CPPFLAGS="-march=x86-64"
        ONEJAR="ON"
        ORG_GRADLE_PROJECT_TILEDB_S3="ON"
install:
  # Build and install extension module
  - ./gradlew assemble test
  # Build oneJar for contained dependencies
  - if [[ "${ONEJAR}" == "ON" ]]; then
      ./gradlew oneJar;
    fi
script:
  - ./gradlew checkFormat
  - ./gradlew test

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export PROJECT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')

deploy:
  provider: releases
  api_key:
    secure: k05zguWwu4I7cGdSwysTCqM3gkEf31s5DWdUuDHvYX7W47biugdSfN4b31Rf2Gimsk3fK7AhV5Givfo30bl4Tv8FCgDgSz4rRR2jrdNkorzPWeYKFyexBnRRY3b4ETWdgNWeGlvRKppDtVlTOSpD4iE/xiyZs4cSiCsGSpHIZ8gw8VjtWnftTd3e0a8oFZ0FmPoV1FRkAslDs4I/KHDwVRXrpFlz3hwqn+SLyxjz4PeASH9fIJJ8ah/QmDPBEnl1zhWzm+tw6nEt5HozGI9FgkwvWCvMGjUSnyxeB/DiG0/rZYO6L5Tw8oBNjnTaJrS4FivxZ9FYcxZ86mCMehh8k03mmPKO/ijW7eRF424aRl/UvpyspvvDjq68omM+uxqBHCn2d+f2NAsosjlAf78gnHHss46sygj200/NbnzQ+HQWI2WhsGem1QO6e1EEiAz8dqln+XL6YZsQi4nWK7XGaT0uyPDUXmP7qasPLkBuDr36CeYAsqcDIEbjtHRIksHBElRX56ZxSygIGcb3Ok5gnmDS5SGY48i/OQSOhD3z1kr6yRGZehZGzNhRIhX70pLeZHuWNLzkJY1krZE1VtqFoxcylamtVpznbsC8ntDJPIyFaMAK+Lg3PA23DomyTQnO3WnkNK2RjKYJKX94ViMgmWeqbvXb/WSOKOOe4LnlXGw=
  skip_cleanup: true
  file: "build/libs/tiledb-java-${PROJECT_VERSION}-standalone.jar"
  on:
    repo: TileDB-Inc/TileDB-Java
    tags: true
    condition: $ONEJAR = "ON"
