version: 0.2.7.{build}

image: Visual Studio 2019
platform:
  - x64

build: off

build_script:
  - mkdir build
  - gradlew assemble

test_script:
  - gradlew test
# Check that the NativeLibLoader functions correctly
  - java -cp build\libs\tiledb-java-*.jar examples.io.tiledb.java.api.TileDBVersion

artifacts:
  - path: 'build\libs\*'
