# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
      - release-*
  tags:
    include:
      - "*"

jobs:
    - job: Windows
      strategy:
        matrix:
          VS2019:
            imageName: 'windows-2019'
            TILEDB_S3: ON
      pool:
        vmImage: $(imageName)
      steps:
        - task: Gradle@2
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew.bat'
            gradleOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: 'default'
            tasks: 'assemble test'

    - job: Linux_OSX
      strategy:
        matrix:
          ubuntu_18:
            imageName: 'ubuntu-18.04'
          macOS:
            imageName: 'macOS-10.14'
      pool:
        vmImage: $(imageName)
      steps:
        - template: ci/tiledb-java-azure.yml